### ISSUE TITLE
Error - "Choose website" is the end

### ISSUE THREAD

**Issue by matomoto** [innocraft/plugin-InvalidateReports#5]
Hello,
i have a problem.

Matomo 3.3.0
InvalidateReports (v0.1.1) Active
More than 10 websites in this matomo instance.

![invalidatereports-001](https://user-images.githubusercontent.com/35422079/35053958-d7649598-fbab-11e7-9bbd-63d6c53c5a78.png)

Firefox 57.0.4 Developer Tools Console:
```
Error: [$controller:ctrlreg] http://errors.angularjs.org/1.6.5/$controller/ctrlreg?p0=InvalidateReportsController
Stack trace:
K/<@https://www.example.com/piwik/index.php?module=Proxy&action=getCoreJs&cb=e45eed5624c2e14c27c2a14855fc3963:126:76
zf/this.$get</<@https://www.example.com/piwik/index.php?module=Proxy&action=getCoreJs&cb=e45eed5624c2e14c27c2a14855fc3963:213:190
ea@https://www.example.com/piwik/index.php?module=Proxy&action=getCoreJs&cb=e45eed5624c2e14c27c2a14855fc3963:196:100
q@https://www.example.com/piwik/index.php?module=Proxy&action=getCoreJs&cb=e45eed5624c2e14c27c2a14855fc3963:187:296
f@https://www.example.com/piwik/index.php?module=Proxy&action=getCoreJs&cb=e45eed5624c2e14c27c2a14855fc3963:181:288
da/<@https://www.example.com/piwik/index.php?module=Proxy&action=getCoreJs&cb=e45eed5624c2e14c27c2a14855fc3963:180:416
S/<@https://www.example.com/piwik/index.php?module=Proxy&action=getCoreJs&cb=e45eed5624c2e14c27c2a14855fc3963:186:65
d@https://www.example.com/piwik/index.php?module=Proxy&action=getCoreJs&cb=e45eed5624c2e14c27c2a14855fc3963:183:41
m@https://www.example.com/piwik/index.php?module=Proxy&action=getCoreJs&cb=e45eed5624c2e14c27c2a14855fc3963:187:88
compile/<@https://www.example.com/piwik/index.php?module=Proxy&action=getCoreJs&cb=e45eed5624c2e14c27c2a14855fc3963:438:311
Qa/<@https://www.example.com/piwik/index.php?module=Proxy&action=getCoreJs&cb=e45eed5624c2e14c27c2a14855fc3963:136:132
ua@https://www.example.com/piwik/index.php?module=Proxy&action=getCoreJs&cb=e45eed5624c2e14c27c2a14855fc3963:204:361
q@https://www.example.com/piwik/index.php?module=Proxy&action=getCoreJs&cb=e45eed5624c2e14c27c2a14855fc3963:190:28
f@https://www.example.com/piwik/index.php?module=Proxy&action=getCoreJs&cb=e45eed5624c2e14c27c2a14855fc3963:181:288
f@https://www.example.com/piwik/index.php?module=Proxy&action=getCoreJs&cb=e45eed5624c2e14c27c2a14855fc3963:181:305
q@https://www.example.com/piwik/index.php?module=Proxy&action=getCoreJs&cb=e45eed5624c2e14c27c2a14855fc3963:189:471
ia/<@https://www.example.com/piwik/index.php?module=Proxy&action=getCoreJs&cb=e45eed5624c2e14c27c2a14855fc3963:200:141
k/<@https://www.example.com/piwik/index.php?module=Proxy&action=getCoreJs&cb=e45eed5624c2e14c27c2a14855fc3963:255:167
$digest@https://www.example.com/piwik/index.php?module=Proxy&action=getCoreJs&cb=e45eed5624c2e14c27c2a14855fc3963:266:70
$apply@https://www.example.com/piwik/index.php?module=Proxy&action=getCoreJs&cb=e45eed5624c2e14c27c2a14855fc3963:269:279
l@https://www.example.com/piwik/index.php?module=Proxy&action=getCoreJs&cb=e45eed5624c2e14c27c2a14855fc3963:221:393
zg/</s.onload@https://www.example.com/piwik/index.php?module=Proxy&action=getCoreJs&cb=e45eed5624c2e14c27c2a14855fc3963:227:297
 <div ng-transclude="">
index.php:242:467
```

**Comment by tsteur** [comment]
Can you try to clear your Matomo (Piwik) cache directory see https://matomo.org/faq/how-to/faq_25548/ ?

**Comment by matomoto** [comment]
Thanks. solved.
Please give me a answer of my question in the closed issues/4.
What means "last month" by "Choose how far back to invalidate data"?
My Matomo instance generate one "archive_xxxx_xx" database table per month.
...
archive_2017_12
archive_2018_01
Means "last month" on today 2017_12 or 2018_01?
Is it necessary to wait for database changes in this month to be corrected with this plugin?

**Comment by tsteur** [comment]
I would say last month means `2017_12` in this case.

Awesome glad it works now. Not sure what you mean changes in this month to be corrected? If something is still unclear I recommend you ask in the forums https://forum.matomo.org or create a new issue

**Comment by Commifreak** [comment]
Hi. Same problem, clearing cache does not solved the issue. Matomo 3.5.1.

Any ideas?

**Comment by dev-101** [comment]
Thanks, had the same issue today, almost opened one. I think this should be added to the plugin's FAQ / download page in red bold :)
